// Generated by tools/i18n/gen-types.ts — do not edit by hand.
// Regenerate with `bun run gen:i18n`; `bun run check:i18n` fails when this drifts.

import type { LocaleId } from '@bale/shared';

export type GlossaryKey =
  | 'gotong_royong.def'
  | 'gotong_royong.term'
  | 'pancaroba.def'
  | 'pancaroba.term'
  | 'pasaran.def'
  | 'pasaran.term'
  | 'sawah.def'
  | 'sawah.term'
  | 'subak.def'
  | 'subak.term'
  | 'tengkulak.def'
  | 'tengkulak.term';

export type UiKey =
  | 'app.tagline'
  | 'app.title'
  | 'boot.hello'
  | 'boot.placeholder'
  | 'common.back'
  | 'common.cancel'
  | 'common.ok'
  | 'hud.day'
  | 'hud.money'
  | 'hud.stamina'
  | 'pasaran.kliwon'
  | 'pasaran.legi'
  | 'pasaran.pahing'
  | 'pasaran.pon'
  | 'pasaran.wage'
  | 'save.saved'
  | 'save.saving'
  | 'season.hujan'
  | 'season.kemarau'
  | 'settings.graphics'
  | 'settings.graphics.preset_high'
  | 'settings.graphics.preset_low'
  | 'settings.graphics.preset_medium'
  | 'settings.language'
  | 'settings.reduce_motion'
  | 'settings.text_size'
  | 'settings.volume.music'
  | 'settings.volume.sfx'
  | 'ship.summary'
  | 'system.inapp_browser'
  | 'system.rotate_device'
  | 'system.update_ready'
  | 'title.continue'
  | 'title.new_game'
  | 'title.settings'
  | 'weather.clear'
  | 'weather.cloudy'
  | 'weather.rain'
  | 'weather.storm'
  | 'weekday.fri'
  | 'weekday.mon'
  | 'weekday.sat'
  | 'weekday.sun'
  | 'weekday.thu'
  | 'weekday.tue'
  | 'weekday.wed';

/** Every key a caller may pass to `t()`: `ui` keys bare, and all keys namespaced. */
export type I18nKey = UiKey | `glossary:${GlossaryKey}` | `ui:${UiKey}`;

export const GENERATED_NAMESPACES = ['glossary', 'ui'] as const;
export type GeneratedNamespace = (typeof GENERATED_NAMESPACES)[number];

export type BundleLoader = () => Promise<{ readonly default: Readonly<Record<string, string>> }>;

/** Lazy per-namespace loaders; the bundler splits each JSON into its own chunk. */
export const LOCALE_BUNDLES: Readonly<
  Record<LocaleId, Readonly<Record<GeneratedNamespace, BundleLoader>>>
> = {
  en: {
    glossary: () => import('../locales/en/glossary.json'),
    ui: () => import('../locales/en/ui.json'),
  },
  id: {
    glossary: () => import('../locales/id/glossary.json'),
    ui: () => import('../locales/id/ui.json'),
  },
};
