// Generated by tools/i18n/gen-types.ts — do not edit by hand.
// Regenerate with `bun run gen:i18n`; `bun run check:i18n` fails when this drifts.

import type { LocaleId } from '@bale/shared';

export type CalendarKey =
  | 'hijri.jumadil_akhir'
  | 'hijri.jumadil_awal'
  | 'hijri.muharram'
  | 'hijri.rabiul_akhir'
  | 'hijri.rabiul_awal'
  | 'hijri.rajab'
  | 'hijri.ramadan'
  | 'hijri.safar'
  | 'hijri.syaban'
  | 'hijri.syawal'
  | 'hijri.zulhijah'
  | 'hijri.zulkaidah'
  | 'jawa.bakda_mulud'
  | 'jawa.besar'
  | 'jawa.jumadil_akhir'
  | 'jawa.jumadil_awal'
  | 'jawa.mulud'
  | 'jawa.pasa'
  | 'jawa.rejeb'
  | 'jawa.ruwah'
  | 'jawa.sapar'
  | 'jawa.sawal'
  | 'jawa.sela'
  | 'jawa.sura'
  | 'jawa_year.alip'
  | 'jawa_year.be'
  | 'jawa_year.dal'
  | 'jawa_year.ehe'
  | 'jawa_year.je'
  | 'jawa_year.jimakir'
  | 'jawa_year.jimawal'
  | 'jawa_year.wawu'
  | 'masehi.apr'
  | 'masehi.aug'
  | 'masehi.dec'
  | 'masehi.feb'
  | 'masehi.jan'
  | 'masehi.jul'
  | 'masehi.jun'
  | 'masehi.mar'
  | 'masehi.may'
  | 'masehi.nov'
  | 'masehi.oct'
  | 'masehi.sep';

export type GlossaryKey =
  | 'gotong_royong.def'
  | 'gotong_royong.term'
  | 'pancaroba.def'
  | 'pancaroba.term'
  | 'pasaran.def'
  | 'pasaran.term'
  | 'sawah.def'
  | 'sawah.term'
  | 'subak.def'
  | 'subak.term'
  | 'tengkulak.def'
  | 'tengkulak.term';

export type ItemsKey =
  | 'crop.cabai.desc'
  | 'crop.cabai.name'
  | 'crop.padi.desc'
  | 'crop.padi.name'
  | 'crop.singkong.desc'
  | 'crop.singkong.name'
  | 'item.cabai.desc'
  | 'item.cabai.name'
  | 'item.cabai_seed.desc'
  | 'item.cabai_seed.name'
  | 'item.gabah.desc'
  | 'item.gabah.name'
  | 'item.padi_seed.desc'
  | 'item.padi_seed.name'
  | 'item.singkong.desc'
  | 'item.singkong.name'
  | 'item.singkong_seed.desc'
  | 'item.singkong_seed.name'
  | 'tool.hoe.desc'
  | 'tool.hoe.name'
  | 'tool.watering_can.desc'
  | 'tool.watering_can.name';

export type UiKey =
  | 'app.tagline'
  | 'app.title'
  | 'boot.hello'
  | 'boot.placeholder'
  | 'common.back'
  | 'common.cancel'
  | 'common.ok'
  | 'controls.empty_slot'
  | 'controls.hotbar'
  | 'controls.interact'
  | 'controls.select_slot'
  | 'controls.turn_ccw'
  | 'controls.turn_cw'
  | 'hud.clock'
  | 'hud.date'
  | 'hud.date_sub'
  | 'hud.day'
  | 'hud.money'
  | 'hud.stamina'
  | 'pasaran.kliwon'
  | 'pasaran.legi'
  | 'pasaran.pahing'
  | 'pasaran.pon'
  | 'pasaran.wage'
  | 'prayer.ashar'
  | 'prayer.dhuha'
  | 'prayer.dzuhur'
  | 'prayer.isya'
  | 'prayer.maghrib'
  | 'prayer.subuh'
  | 'save.saved'
  | 'save.saving'
  | 'season.hujan'
  | 'season.kemarau'
  | 'settings.graphics'
  | 'settings.graphics.preset_high'
  | 'settings.graphics.preset_low'
  | 'settings.graphics.preset_medium'
  | 'settings.language'
  | 'settings.reduce_motion'
  | 'settings.text_size'
  | 'settings.volume.music'
  | 'settings.volume.sfx'
  | 'ship.summary'
  | 'system.inapp_browser'
  | 'system.rotate_device'
  | 'system.update_ready'
  | 'title.continue'
  | 'title.new_game'
  | 'title.settings'
  | 'weather.clear'
  | 'weather.cloudy'
  | 'weather.rain'
  | 'weather.storm'
  | 'weekday.fri'
  | 'weekday.mon'
  | 'weekday.sat'
  | 'weekday.sun'
  | 'weekday.thu'
  | 'weekday.tue'
  | 'weekday.wed';

/** Every key a caller may pass to `t()`: `ui` keys bare, and all keys namespaced. */
export type I18nKey =
  | UiKey
  | `calendar:${CalendarKey}`
  | `glossary:${GlossaryKey}`
  | `items:${ItemsKey}`
  | `ui:${UiKey}`;

export const GENERATED_NAMESPACES = ['calendar', 'glossary', 'items', 'ui'] as const;
export type GeneratedNamespace = (typeof GENERATED_NAMESPACES)[number];

export type BundleLoader = () => Promise<{ readonly default: Readonly<Record<string, string>> }>;

/** Lazy per-namespace loaders; the bundler splits each JSON into its own chunk. */
export const LOCALE_BUNDLES: Readonly<
  Record<LocaleId, Readonly<Record<GeneratedNamespace, BundleLoader>>>
> = {
  en: {
    calendar: () => import('../locales/en/calendar.json'),
    glossary: () => import('../locales/en/glossary.json'),
    items: () => import('../locales/en/items.json'),
    ui: () => import('../locales/en/ui.json'),
  },
  id: {
    calendar: () => import('../locales/id/calendar.json'),
    glossary: () => import('../locales/id/glossary.json'),
    items: () => import('../locales/id/items.json'),
    ui: () => import('../locales/id/ui.json'),
  },
};
