#!/usr/bin/env bun
/**
 * Generates `packages/content/src/i18n.generated.ts` from the source-locale files:
 *
 * - `I18nKey`, so `t('hud.mony')` is a compile error rather than a runtime `⟦key⟧` (I18N §4).
 * - `LOCALE_BUNDLES`, a per-locale map of lazy namespace loaders, so the client can pull
 *   `ui` at boot and everything else on demand without a hand-maintained registry.
 *
 * The output is committed: `bun run check` must work on a clean checkout without a
 * codegen step first, and `check:i18n` fails when it drifts from the locale files.
 *
 *   bun tools/i18n/gen-types.ts            # write
 *   bun tools/i18n/gen-types.ts --check    # exit 1 if the committed file is stale
 */

import { join } from 'node:path';
import { SOURCE_LOCALE } from '@ndeso/shared';
import { LOCALE_IDS, presentNamespaces, readBundle } from './locales.ts';

export const GENERATED_PATH = join(import.meta.dir, '../../packages/content/src/i18n.generated.ts');

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function pascal(namespace: string): string {
  return namespace.charAt(0).toUpperCase() + namespace.slice(1);
}

function union(keys: readonly string[]): string {
  return keys.length === 0 ? 'never' : keys.map((key) => `\n  | ${quote(key)}`).join('');
}

export async function renderGeneratedModule(): Promise<string> {
  const namespaces = presentNamespaces(SOURCE_LOCALE);
  const lines: string[] = [
    '// Generated by tools/i18n/gen-types.ts — do not edit by hand.',
    '// Regenerate with `bun run gen:i18n`; `bun run check:i18n` fails when this drifts.',
    '',
    "import type { LocaleId } from '@ndeso/shared';",
    '',
  ];

  const keyTypes: string[] = [];
  for (const namespace of namespaces) {
    const bundle = await readBundle(SOURCE_LOCALE, namespace);
    const typeName = `${pascal(namespace)}Key`;
    keyTypes.push(typeName);
    lines.push(`export type ${typeName} =${union(Object.keys(bundle).sort())};`, '');
  }

  // `ui` is the default namespace, so its keys are also valid unqualified (I18N §2).
  const bare = namespaces.includes('ui') ? ['UiKey'] : [];
  const qualified = namespaces.map((ns, i) => `\`${ns}:\${${keyTypes[i]}}\``);
  const members = [...bare, ...qualified];
  lines.push(
    '/** Every key a caller may pass to `t()`: `ui` keys bare, and all keys namespaced. */',
    `export type I18nKey = ${members.length === 0 ? 'never' : members.join(' | ')};`,
    '',
    `export const GENERATED_NAMESPACES = [${namespaces.map(quote).join(', ')}] as const;`,
    'export type GeneratedNamespace = (typeof GENERATED_NAMESPACES)[number];',
    '',
    'export type BundleLoader = () => Promise<{ readonly default: Readonly<Record<string, string>> }>;',
    '',
    '/** Lazy per-namespace loaders; the bundler splits each JSON into its own chunk. */',
    'export const LOCALE_BUNDLES: Readonly<',
    '  Record<LocaleId, Readonly<Record<GeneratedNamespace, BundleLoader>>>',
    '> = {',
  );

  for (const locale of LOCALE_IDS) {
    lines.push(`  ${locale}: {`);
    for (const namespace of namespaces) {
      lines.push(`    ${namespace}: () => import('../locales/${locale}/${namespace}.json'),`);
    }
    lines.push('  },');
  }
  lines.push('};', '');

  return formatWithBiome(lines.join('\n'));
}

/**
 * Hand the output to Biome so the committed file survives `biome check .` unchanged —
 * otherwise `bun run fmt` would reformat it and `--check` would report false drift.
 */
async function formatWithBiome(source: string): Promise<string> {
  const proc = Bun.spawn(
    ['./node_modules/.bin/biome', 'format', '--stdin-file-path=i18n.generated.ts'],
    {
      cwd: join(import.meta.dir, '../..'),
      stdin: new TextEncoder().encode(source),
      stdout: 'pipe',
      stderr: 'pipe',
    },
  );
  const [formatted, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (code !== 0) throw new Error(`biome format failed: ${stderr}`);
  return formatted;
}

if (import.meta.main) {
  const source = await renderGeneratedModule();
  if (process.argv.includes('--check')) {
    const current = await Bun.file(GENERATED_PATH)
      .text()
      .catch(() => '');
    if (current !== source) {
      console.error('i18n types are stale — run `bun run gen:i18n` and commit the result.');
      process.exit(1);
    }
    console.log('i18n generated types are up to date.');
  } else {
    await Bun.write(GENERATED_PATH, source);
    console.log(`wrote ${GENERATED_PATH}`);
  }
}
